[licenses]
allow = [
  "MIT",
  "CC0-1.0",
  "ISC",
  "Unlicense",
]

private = { ignore = true }

[[licenses.clarify]]
name = "ring"
version = "*"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 }
]

[advisories]
ignore = [
    # `net2` crate has been deprecated; use `socket2` instead
    # Solution: No safe upgrade is available!
    # net2 v0.2.34
    "RUSTSEC-2020-0016",

    # Unaligned memory access
    # Solution: Upgrade to >=0.4.2
    # rand_core v0.3.1
    # Require `rand` upgrade in `avro-rs`
    "RUSTSEC-2019-0035",

    # Type confusion if __private_get_type_id__ is overriden
    # Solution: No safe upgrade is available!
    # failure v0.1.8
    "RUSTSEC-2019-0036",
    "RUSTSEC-2020-0036",

    # dirs is unmaintained, use dirs-next instead
    # Solution: No safe upgrade is available!
    # dirs v2.0.2
    "RUSTSEC-2020-0053",

    # stdweb is unmaintained
    # Solution: No safe upgrade is available!
    # stdweb v0.4.20
    # can be removed after next release of `time` crate
    # https://github.com/time-rs/time/commit/8b2734351a5cd05a9bd3315f1af76c28b5852fec
    "RUSTSEC-2020-0056",

    # Some lock_api lock guard objects can cause data races
    # Solution: Upgrade to >=0.4.2
    # lock_api v0.3.4
    "RUSTSEC-2020-0070",

    # GenericMutexGuard allows data races of non-Sync types across threads
    # Solution: Upgrade to >=0.4.0
    # futures-intrusive v0.3.1
    "RUSTSEC-2020-0072",

    # ordered_float:NotNan may contain NaN after panic in assignment operators
    # Solution: Upgrade to >=1.1.1, <2.0.0 OR >=2.0.1
    # ordered-float v2.0.0
    # ordered-float - can be removed when heim next releases their beta branch
    "RUSTSEC-2020-0082",
]
